# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 paths:
   include:
     - result/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'dedc09c1-da54-4ba1-a6b9-7aad948430a9'
  imageRepository: 'result'
  containerRegistry: 'nagacicd.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name (This Runner is for paid account)
  #vmImageName: 'ubuntu-latest'

pool:
 name: 'azureagent-pool' #we created our owner VM as runner to execute below jobs

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    #pool:
      #vmImage: $(vmImageName) #these are not for free trail account
    steps:
    - task: Docker@2
      displayName: Build the image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'result/Dockerfile'
        tags: '$(tag)'
- stage: Push
  displayName: Push
  jobs:
  - job: Push
    displayName: Push
    #pool:
      #vmImage: $(vmImageName) #these are not for free trail account
    steps:
    - task: Docker@2
      displayName: push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'
